version: 2
registries:
  terraform-cloud:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{ secrets.TFCLOUD_API_KEY }}
updates:
  - package-ecosystem: terraform
    directory: "/"
    registries:
      - terraform-cloud
    labels:
      - "dependencies"
      - "standard_change"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
